---

- name: reload systemd
  systemd:
    daemon_reload: true
  when: ansible_distribution_release in ['bionic'] and ansible_service_mgr == 'systemd'

- name: reload supervisor
  command: supervisorctl reload
  notify: remove celerybeat schedule

# The schedule file becomes corrupted between updates.
- name: remove celerybeat schedule
  file:
    path: "{{ openwisp2_path }}/celerybeat-schedule.db"
    state: absent

- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: start redis
  when: openwisp2_redis_install
  service:
    name: redis
    state: started
